### ISSUE TITLE
OC Only: Headless mode with autoqueries

### ISSUE THREAD

**Issue by enketo-issue-mover** [OpenClinica/enketo-express-oc#47]
_From @MartijnR on July 19, 2016 19:45_

Needs to be able to handle large import loads. 

Enketo Express or stand-alone app? Advantages of both: 

| Enketo Express | Standalone |
| --- | --- |
|  | performance, easily scaleable |
|  | imports will not affect regular webforms loading/submissions |
| cheaper to develop |  |
| easier to maintain code (more re-use) |  |
| no extra app to run |  |
| transformer and core automatically in sync |  |

_Copied from original issue: kobotoolbox/enketo-express#533_

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on July 20, 2016 19:40_

- record-per-record
- returning list of errors

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on July 22, 2016 21:46_

as discussed: dedicated "record-validator" Enketo Express instance could be used to get benefits of both columns in above table. Simply don't use the instance for anything else...

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on August 10, 2016 21:29_

Possibly need to add check for whether irrelevant branches have values in them (they shouldn't). Thanks @dorey! :)

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on July 31, 2017 21:48_

for OC might need to be combined with auto-queries, and maybe calculations should be run

Maybe this issue would need to be renamed to just running headlessly and return an automatically edited record (autoqueries, calcs, relevants). If record marked as complete, there would be special issues perhaps (such as needing to empty irrelevant fields manually).

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on January 29, 2018 20:45_

The goal is to get autoqueries added.

What kind of results are expected from such a request? A bunch of fieldsubmissions?

Views: could be a complete or incomplete record in edit mode (so with or without complete button). If RFC required, needs auto-RFC (new feature). May just need to add RFC field to API call and populate with that value.  If param not provided used hardcode default perhaps.

Another use case: form changed -> need to run calcs, contraints, relevants.

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on March 7, 2018 20:30_

complete record with or without RFC
incomplete record which would have to be loaded and then either Closed or Completed

Possible change in autoqueries:
- If irrelevant field has value (when record is loaded) the relevant autoquery needs to be added (may currently not be the case in "headfull" mode.

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on June 6, 2018 19:16_

Like edit view:
* always click Close button to trigger autoqueries and finish (after fieldsubmission have completed).
* for incomplete records, the close dialog option for "use queries" should be selected automatically
* different views for RFC and no-RFC

Differs from edit view:
* ~~pass RFC value (one string)~~
* probably need different view for completed and incomplete records (because Close button works differently currently for complete and incomplete records). 
* relevantErrors current have no autoqueries but need to get them.

Should we figure out how to properly mark a record as complete first? #972

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on June 7, 2018 22:9_

for testing (with Centro): http://localhost:8005/single/fs/i/::uEUZO5H2

This approach will be feasible. Fieldsubmissions are taking place when running headlessly. If a possible scenario is to run large batches of records through this feature programmatically, I think we should probably run this on its own server, so regular data collection is not affected. The server load is probably high in this scenario (higher than with regular simultaneous data collection) because it's actually running the surveys on the server instead on the user's device.

* [x] figure out how to avoid launching multiple browsers and how to re-launch a browser after it crashes
* [x] make appropriate pdf logic changes (using one browser instance ???)
* [x] create special views that perform the auto-stuff and send a message when the queue is empty
* [x] have timeout and figure out how to deal with records that were only partially submitted
* [x] make sure to catch exceptions and close the browser when they occur. Otherwise it keeps running! - or timeout does that
* [x] after completion some kind of call has to be made so OC knows it didn't time out -> seems better for OC to just read response of API call
* [x] maintain counter of successful fieldsubmissions.
* [x] ~~"instance "_users" does not exist in model" not returned (returns 201??) (is a DN error)~~
* [x] failed to emtpy queue: should output error -> timeout or 'Failed to submit' depending on issue
* [x] document API endpoints
* [x] require instance in API -> test
* [x] complete vs. incomplete autoquery logic after #972 has been completed
* [x] load form with loading error -> response 400
* [x] load form with uncaught exception -> response 400
* [x] remove RFC headless view for now
* [x] new encryption keys for headless views? (re-using unencrypted id for non-RFC and regular RFC encrypted id for RFC headless now
* [x] fix oc: namespace resolving issue if form doesn't have oc namespace declaration https://github.com/kobotoolbox/enketo-express/issues/1111
* [x] fix broken tests - switch to grunt-contrib-uglify-es (in kobotoolbox/enketo-express) https://github.com/kobotoolbox/enketo-express/issues/1113
* [x] if exception occurs (tested with fieldsubmissions failure), no "code" property in response - Never mind that is by design to never return a code.
* [x] test with failed /fieldsubmission/complete response
* [x] test with autoqueries-making-valid
* [x] fix validation not functioning (nothing invalidates when form.validate is called programmatically) - I don't understand why it works with 1ms delay but not without. -> https://github.com/enketo/enketo-core/issues/543
* [x] fix unhandled promise rejection upon /fieldsubmission
* [x] handle errors that are caused by autoqueries, maybe loop 3 times? 
* [x] remove code from response
* [x] ~~mechanism to pass auto-RFC message~~
* [x] ~~disable pages mode (for RFC fields?)~~
* [x] ~~RFC would never have a complete button~~
* [x] ~~How to trigger RFC requirement? Normally calculated items upon load will not create an RFC field (because widgets initializes after calculations).~~

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on June 15, 2018 19:16_

1-2 weeks depending on complexity of logic

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on June 21, 2018 21:11_

response is best done in the same manner as other API response so with HTTP status code and JSON response body:

2xx
{
  message: "OK",
  code: 2xx
}

200: OK, but no fieldsubmissions were made (hence no autoqueries were added either)
201: OK, fieldsubmissions were created and all submitted successfully
408: timeout, something went wrong, some fieldsubmissions may have been made, see message for details?
400: some other browser error occured before the timeout was exceeded. The process was stopped.
500: unknown server error

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on June 22, 2018 20:29_

am experiencing this issue: https://github.com/GoogleChrome/puppeteer/issues/1047

Can be avoided by not using the fancy self-spawning upon crash but creating a new instance for each request and closing the browser afterwards

Checking if the actual cause was not closing the page when an error occurred.

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on September 7, 2018 0:1_

@pbowen-oc, what should be the difference in behavior in between these scenarios?

1. Process a record that is marked as complete
2. Process a record that is not marked as complete

**Comment by enketo-issue-mover** [comment]
_From @pbowen-oc on September 7, 2018 0:15_

@MartijnR - Records marked complete would need to have autoqueries added for any error (constraint, required, relevant). I think records not marked complete would only get autoqueries for constraint and relevant errors (not required errors).

Regarding our recent discussion of strict constraint/required, I think this behavior would apply equally to strict and non-strict constraint/required errors. Perhaps, though, in the case of a strict constraint/required error being active, a different response should be sent back to OC so that we can flag the record if needed?

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on September 7, 2018 19:52_

* [x] validation issue is the same in regular fieldsubmission view without enketo-core customizations and common KoBo views
* [x] check kobo/enketo-express - http://localhost:8005/::YY80 - No issue

It's definitely something that is OC fork only

problem is:

Form.init customization includes asynchronous function that sets invalid required fields to valid... This should be taken outside of form.init. It's also not clear why this is in a try catch block.

The other issue is in relevant.js.

**Comment by enketo-issue-mover** [comment]
_From @MartijnR on September 7, 2018 22:16_

Ready for testing in `develop` branch. 

Documentation: https://github.com/OpenClinica/enketo-express-oc/blob/develop/doc/oc-api.md#post-instanceheadless

P.S. not including a Participate version of this endpoint & view.

**Comment by pbowen-oc** [comment]
I'll need to test this with strict constraints/requireds. They should generate autoqueries just like non-strict constraints/requireds.

**Comment by pbowen-oc** [comment]
We'll need to make sure this interacts with the multiple queries feature correctly with respect to the autoqueries added. They should work the same as in headful views.

We'll also need to add a corresponding RFC headless view. I think we'll need to be able to pass in an RFC string to be applied for any value that is updated due to a calculation. Other than applying that automatically, I think it should work the same as the headful RFC view.

For strict constraint/required, we'll want the autoqueries to work the same way they do in headful views.

For the new functionality you are currently adding for autoqueries for relevant errors (matching the behavior of strict constraints), we'll want the headless behavior to match the headful behavior.

**Comment by MartijnR** [comment]
Some diff in logic with RFC (e.g. required errors get autoquery).

Note in the future there may also be a particpant/headless view.

**Comment by MartijnR** [comment]
* [ ] consider overwriting the gui functions so the existing close/complete functions can be used instead

**Comment by MartijnR** [comment]
/instance/headless
/instance/headless/rfc
/instance/headless/participate (future)

**Comment by MartijnR** [comment]
* [ ] headless/rfc with required rfc (message) parameter

**Comment by pbowen-oc** [comment]
I don't think there is a case since we don't include RFC entries for calculated values. I need to verify.

**Comment by MartijnR** [comment]
* [ ] an error message (e.g. missing RFC) is not properly returned in response (instead 408: timeout exceeded)

**Comment by MartijnR** [comment]
@pbowen-oc I believe that the regular (non-RFC) headless view should never return a record-validation error or fieldsubmission error, since in the non-headless view everything can be bypassed by the user. Is that correct?

**Comment by pbowen-oc** [comment]
@MartijnR - That sounds about right. All issues can be bypassed with queries in the non-RFC view. As long as any calculations and/or queries are submitted successfully, then it should pass. However, I could still see a case for a fieldsubmission error to occur due to a server or configuration issue.

For the RFC view, I think the only thing that blocks closing the form now is not entering a required RFC. Since we will not be requesting RFC in this headless mode, I think the same job statusl logic applies to the RFC view and non-RFC view.

**Comment by MartijnR** [comment]
Thanks, I think the difference is in whether Close or Complete is used. I am not sure if this is something I made up myself or was part of the requirements but currently:

* any final records will go through **Complete** logic (in both RFC and regular views)
* and non-final records (only in regular views) will go through  **Close** logic.

Close logic doesn't currently prevent closing if fieldsubmissions have failed (users can bypass with Confirm)

**Comment by pbowen-oc** [comment]
@MartijnR - The headless mode should use the Close button to finish with the record. We'll either pass in an incomplete form to the regular view or a complete form to the RFC view. It should not click the Complete button in either case.

If the form does not finish processing completely successfully (e.g., fieldsubmission fails), I think the job should end and report back that an error was encountered.

**Comment by MartijnR** [comment]
* [ ] output submission errors
* [ ] in any case always output successful submissions

**Comment by MartijnR** [comment]
see documentation here (2 headless API endpoints): https://github.com/OpenClinica/enketo-express-oc/blob/develop/doc/oc-api.md#post-instanceheadless

**Comment by MartijnR** [comment]
* [ ] make sure ecid is included in returned URL, and make it a required param (like the other endpoints
